### PR TITLE
feat: additional parameters to putObject

### PR DESCRIPTION
**Pull request by aattola**
Adds additional parameters to putObject so you can set additional fields to requests.

### CODE REVIEW

**Comment by zabkwak** [comment]
Hi, thank you for the PR. Where are the data stored? How do you access it in the future?

**Comment by aattola** [comment]
I am not sure what you mean by that. This pull request only adds functionality to pass along extra parameters with the put request.

**Comment by zabkwak** [comment]
I understand that. But what's the difference from the metadata? If you pass metadata to the object you can access them with headers.

**Comment by aattola** [comment]
Scaleway has some custom headers that cannot be prefixed with  x-amz-meta

**Comment by zabkwak** [comment]
And this is working? I was never able to put additional data instead of meta headers :(

**Comment by aattola** [comment]
I got this code to upload the file and set it public at the same time using the additional fields.
`storage.putObject(BUCKET, 'publictest.txt', 'Test file content', undefined, undefined, { testTag: 'test' }, {"x-amz-acl": "public-read"})`

**Comment by zabkwak** [comment]
Okay. That's cool.

**Comment by aattola** [comment]
Could you release this to npm when you have time?

**Comment by zabkwak** [comment]
Sure. Give me second :)

**Comment by zabkwak** [comment]
It's there

**Comment by aattola** [comment]
Thank you!

**Pull request merged**
